import { test, expect } from '@playwright/test';

test('POST request to create a new post', async ({ request }) => {
  // This test demonstrates how to send a POST request to create new data on the server
  // POST requests are used to submit data to be processed to a specified resource
  // The JSONPlaceholder API simulates creating a post and returns the created object with an id

  // Define the data we want to send in the POST request
  const newPost = {
    title: 'My Test Post',
    body: 'This is the body of my test post for API testing.',
    userId: 1,
  };

  // Send a POST request to the /posts endpoint with the new post data
  const response = await request.post('https://jsonplaceholder.typicode.com/posts', {
    data: newPost, // The data to send in the request body
  });

  // Assert that the HTTP status code is 201, which indicates the resource was created successfully
  // Status code 201 means "Created"
  expect(response.status()).toBe(201);

  // Parse the response body as JSON to get the created post
  const createdPost = await response.json();

  // Assert that the response includes the original data we sent
  expect(createdPost.title).toBe(newPost.title);
  expect(createdPost.body).toBe(newPost.body);
  expect(createdPost.userId).toBe(newPost.userId);

  // Assert that the server assigned an id to the new post
  expect(createdPost).toHaveProperty('id');
  expect(typeof createdPost.id).toBe('number');

  // Note: In a real API, the id would be generated by the server
  // JSONPlaceholder simulates this by returning an id (usually 101 for new posts)
});